### ISSUE TITLE
Can't add categories and hourly rate

### ISSUE THREAD

**Issue by sadovnik** [ArbeitBot/ArbeitBot#5]
When I select "Add categories" or "Add hourly rate" the bot responds with "Media unsupported".
![screenshot](https://www.dropbox.com/s/6tdbo548n5g8umw/Screen%20Shot%202016-10-28%20at%2023.30.11.png?dl=1)

My username is cyril_sadovnik. Any ideas?

**Comment by backmeupplz** [comment]
@sadovnik thank you a lot for reporting this! Please update your Telegram version, looks like this might be related to inline keyboards that were introduced relatively recently: https://core.telegram.org/constructor/messageMediaUnsupported. Please let us know if the issue is gone after updating the Telegram app.

**Comment by sadovnik** [comment]
After update it's all good now. Thanks!
